// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5d8Lr7_xwWJuGQtV6Ku9ImAwslvjMsIg',
    appId: '1:776936991877:web:77d8211de11f865d6b4dec',
    messagingSenderId: '776936991877',
    projectId: 'planney-1d548',
    authDomain: 'planney-1d548.firebaseapp.com',
    storageBucket: 'planney-1d548.appspot.com',
    measurementId: 'G-VP5J2MY1NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjMiuFxsiQVg4WTdAdo-h-VtctZ3km-og',
    appId: '1:776936991877:android:5bd1f42b94ba259b6b4dec',
    messagingSenderId: '776936991877',
    projectId: 'planney-1d548',
    storageBucket: 'planney-1d548.appspot.com',
  );
}
